//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bibliotecaEntities : DbContext
    {
        public bibliotecaEntities()
            : base("name=bibliotecaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbCategoria> tbCategorias { get; set; }
        public virtual DbSet<tbCliente> tbClientes { get; set; }
        public virtual DbSet<tbHistorico> tbHistoricoes { get; set; }
        public virtual DbSet<tbLibro> tbLibroes { get; set; }
        public virtual DbSet<tbPersona> tbPersonas { get; set; }
        public virtual DbSet<tbUsuario> tbUsuarios { get; set; }
    }
}
