//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHistorico
    {
        public int id { get; set; }
        public int idCliente { get; set; }
        public int idLibro { get; set; }
        public System.DateTime fechaPrestamo { get; set; }
        public Nullable<System.DateTime> fechaDevolucion { get; set; }
    
        public virtual tbCliente tbCliente { get; set; }
        public virtual tbLibro tbLibro { get; set; }
    }
}
